#
# Sample firmware for my ESP32 PoE ethernet dev board
#
# NOTE: Only IDF v4 / Arduino 2.0 support the RTL PHY. See:
# https://github.com/esphome/feature-requests/issues/1462
#

substitutions:
  device_name: dali_master
  device_description: PoE DALI Master

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_description}
  name_add_mac_suffix: true

esp32:
  board: esp32dev

ethernet:
  type: RTL8201
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_OUT
  phy_addr: 0

external_components:
  - source: 
      type: local
      path: components

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
  - platform: esphome
    password: !secret ota_password

logger:

light:

- platform: dali
  id: dali_light_0
  name: "DALI Light"
  address: 0  # Short address, Group address, or 0xFF for broadcast
  restore_mode: RESTORE_DEFAULT_ON 

output:

# bit-banged DALI bus
dali:
  id: dali_bus
  tx_pin: 4
  rx_pin: 12
